[FIO toup] gpu: drm: cadence: select hdmi helper
drm_hdmi_helper driver is required for cdns-hdmi-core driver to be
built well. Select the option DRM_DISPLAY_HDMI_HELPER to fix building
error [1].

[1]
aarch64-none-linux-gnu-ld: drivers/gpu/drm/bridge/cadence/cdns-hdmi-core.o: in function `cdns_hdmi_mode_set':
cdns-hdmi-core.c:(.text+0xfec): undefined reference to `drm_hdmi_avi_infoframe_colorimetry'
aarch64-none-linux-gnu-ld: cdns-hdmi-core.c:(.text+0x10ac): undefined reference to `drm_hdmi_infoframe_set_hdr_metadata'

Upstream-Status: Pending

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>